package com.sterning.books.model;

// Generated 2014-7-21 15:19:07 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Books generated by hbm2java
 */
public class Books implements java.io.Serializable {

	private String id;
	private String bookId;
	private String author;
	private String content;
	private Date dateComment;
	private String source;

	public Books() {
	}

	public Books(String bookId, String author, String content) {
		this.bookId = bookId;
		this.author = author;
		this.content = content;
	}

	public Books(String bookId, String author, String content, Date dateComment, String source) {
		this.bookId = bookId;
		this.author = author;
		this.content = content;
		this.dateComment = dateComment;
		this.source = source;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getBookId() {
		return this.bookId;
	}

	public void setBookId(String bookId) {
		this.bookId = bookId;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getDateComment() {
		return this.dateComment;
	}

	public void setDateComment(Date dateComment) {
		this.dateComment = dateComment;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

}
